name: Download Full 3-4-5 Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  download_syzygy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare directories
        run: |
          mkdir -p engines/syzygy/wdl
          mkdir -p engines/syzygy/dtz

      - name: Download and extract 3-4-5 WDL
        run: |
          curl -L https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl -o wdl.zip
          unzip -q wdl.zip -d engines/syzygy/wdl
          rm wdl.zip

      - name: Download and extract 3-4-5 DTZ
        run: |
          curl -L https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz -o dtz.zip
          unzip -q dtz.zip -d engines/syzygy/dtz
          rm dtz.zip
